
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 20 19:10:20 CST 2022
//----------------------------------------------------

package ejerciciojflex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 56;
  public static final int Asig = 7;
  public static final int Entero = 59;
  public static final int True = 47;
  public static final int Coma = 41;
  public static final int Nulo = 3;
  public static final int Negacion = 55;
  public static final int main = 38;
  public static final int If = 18;
  public static final int Id = 14;
  public static final int ExprLogica = 5;
  public static final int IgualIgual = 49;
  public static final int LlaveC = 36;
  public static final int Diferente = 50;
  public static final int LlaveA = 37;
  public static final int Default = 27;
  public static final int Operador = 13;
  public static final int CharType = 58;
  public static final int Separador = 8;
  public static final int Menor = 51;
  public static final int Else = 19;
  public static final int Read = 43;
  public static final int Break = 25;
  public static final int Mayor = 53;
  public static final int ExprFinal = 9;
  public static final int Return = 24;
  public static final int While = 21;
  public static final int Division = 33;
  public static final int Int = 16;
  public static final int Flotante = 4;
  public static final int Float = 45;
  public static final int Cadena = 11;
  public static final int For = 22;
  public static final int EOF = 0;
  public static final int DosPuntos = 42;
  public static final int And = 57;
  public static final int CorcheteC = 40;
  public static final int error = 1;
  public static final int CorcheteA = 39;
  public static final int Switch = 23;
  public static final int False = 48;
  public static final int Tipo = 2;
  public static final int Char = 15;
  public static final int EstruControl = 12;
  public static final int Print = 28;
  public static final int ERROR = 44;
  public static final int Case = 26;
  public static final int DecInc = 20;
  public static final int MenorIgual = 52;
  public static final int Parametros = 32;
  public static final int String = 17;
  public static final int Resta = 31;
  public static final int MayorIgual = 54;
  public static final int Bool = 46;
  public static final int ParentesisC = 34;
  public static final int Boolean = 6;
  public static final int Multiplicacion = 29;
  public static final int ParentesisA = 35;
  public static final int Suma = 30;
  public static final int Comillas = 10;
}

